### ISSUE TITLE
Request for new v0.5.4 release

### ISSUE THREAD

**Issue by sethp-verica** [google/gnostic#237]
Hello! I'm seeing the following when using a mix of `go get` clients that use the module proxy and those that don't (in my case, the latter being dependabot):

```
go: downloading github.com/googleapis/gnostic v0.5.3
verifying github.com/googleapis/gnostic@v0.5.3: checksum mismatch
	downloaded: h1:FP6YXyar5+eeXU8lBWDHJMZLHinornnILMJYBLgqKXk=
	go.sum:     h1:2qsuRm+bzgwSIKikigPASa2GhW8H2Dn4Qq7UxD8K/48=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

I can reproduce this by:

```
cd $(mktemp -d)
go mod init example.com/m
go clean -modcache
go get github.com/googleapis/gnostic@v0.5.3
go clean -modcache
GOPRIVATE=* go get github.com/googleapis/gnostic@v0.5.3
```

The proxy looks like it's serving 42aec32c, but the commit currently pointed to by the `v0.5.3` tag is e21f2384. I'm able to work around this for my module by adding a `replace` to my go.mod to point explicitly to e21f2384:

```
replace github.com/googleapis/gnostic v0.5.3 => github.com/googleapis/gnostic v0.0.0-20201026162421-e21f238441d2
```

but it seems like there are at least [two](https://github.com/vmware-tanzu/octant/blob/19d75052e26e2b580146c12a827516f98ca137ce/go.sum#L329) [other](https://github.com/google/skia-buildbot/blob/master/go_repositories.bzl#L1252) modules that are depending on the older version, and at least one other project [running into the same dependabot problem](https://github.com/SeldonIO/seldon-core/pull/2775#issuecomment-747550858).

 I [asked](https://gophers.slack.com/archives/C9BMAAFFB/p1611258475037100 ) in the #modules channel of the Go slack, and it seems like the proxy is behaving as expected here:

> Once a tag is created, it should not be deleted or changed to a different revision. Versions are authenticated to ensure safe, repeatable builds. If a tag is modified, clients may see a security error when downloading it. Even after a tag is deleted, its content may remain available on module proxies.
– https://golang.org/ref/mod#vcs-version

It seems to me the best way to resolve the ambiguity here is to cut a v0.5.4 release that both github and the module proxy agree points to e21f2384. What do you think?

**Comment by timburks** [comment]
Sorry about the messiness! I've just pushed a v0.5.4 that points to e21f238 and repointed v0.5.3 at 42aec32.
