### ISSUE TITLE
Security checksum error when vendoring google/gnostic

### ISSUE THREAD

**Issue by alecholmez** [google/gnostic#238]
When vendoring this repo on alpine 3.13 the following happens: 
```
go: downloading github.com/googleapis/gnostic v0.5.3
verifying github.com/googleapis/gnostic@v0.5.3: checksum mismatch
	downloaded: h1:2qsuRm+bzgwSIKikigPASa2GhW8H2Dn4Qq7UxD8K/48=
	go.sum:     h1:FP6YXyar5+eeXU8lBWDHJMZLHinornnILMJYBLgqKXk=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

This does not happen on mac os, have tried to specify GOPROXY and GOSUMDB, also tried running `go clean -modcache` to no luck. Any insight would be helpful!

**Comment by dprotaso** [comment]
We're seeing this as well - was the `v0.5.3` tag rewritten?

**Comment by dprotaso** [comment]
Even the golang sum db has the older sha

https://sum.golang.org/lookup/github.com/googleapis/gnostic@v0.5.3

**Comment by dprotaso** [comment]
oh nm - i misread go sum db seems to match the downloaded version now

**Comment by dprotaso** [comment]
@alecholmez what's your `GOPROXY` setting - we're using `direct` so I wonder if that's it

**Comment by alecholmez** [comment]
I had goproxy=direct and gosumdb=off

**Comment by dprotaso** [comment]
So I confirmed that v0.5.3 was re-tagged to include the commit 
https://github.com/google/gnostic/commit/e21f238441d25c98901a99d17f154f118f642e1a

**Comment by dprotaso** [comment]
golang's proxy server has v0.5.3 pointing to https://github.com/google/gnostic/commit/42aec32c2aea3caa57419d923d456f01f1e51edf

**Comment by dprotaso** [comment]
this is also a dupe of https://github.com/google/gnostic/issues/237

**Comment by timburks** [comment]
Repeating from #237: Sorry about the messiness! I've just pushed a v0.5.4 that points to e21f238 and repointed v0.5.3 at 42aec32.
