### ISSUE TITLE
Add "type: object" to schemas for protoc-gen-openapi

### ISSUE THREAD

**Issue by micmorris** [google/gnostic#263]
I'm trying to get [Twilio's Guardrail](https://github.com/guardrail-dev/guardrail) to generate Akka endpoints based on OpenAPI, but it's choking on schemas lacking the `type` field with "Error:Unknown type".

I see in the [OpenAPI spec](https://swagger.io/docs/specification/data-models/data-types/) that `type` is *technically* optional, but it mean that the field can be *any* type, but in this situation, I think these can be clearly considered `objects`.

I made this one-line change locally and verified it worked, add a new line between [Line 596-597](https://github.com/google/gnostic/blob/master/apps/protoc-gen-openapi/generator/openapi-v3.go#L596):

`Type: "object",`

**Comment by jeffsawatzky** [comment]
@micmorris / @timburks the linked PR is closed so I think this issue can be closed too.

**Comment by micmorris** [comment]
Awesome, thanks to both of you!
