### ISSUE TITLE
 Explicit 'optional' labels are not supported

### ISSUE THREAD

**Issue by maxlein** [google/gnostic#275]
I can't build my swagger services because optionals are not allowed.  

`simple_rpc.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-openapi hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.--openapi_out: `  

Is there any work done yet?

**Comment by morphar** [comment]
Hi @maxlein, I have done some work on the protoc-gen-openapi and I may be able to add optional.
Do you have an example of the proto file that fails? Just a simple example with the optional will do.
If you also have an example of the expected Open API file output, that would also be helpful.

**Comment by maxlein** [comment]
Here you go:  

```protobuf
syntax = "proto3";

import "google/api/annotations.proto";
import "google/api/client.proto";

// we build swagger config with https://github.com/google/gnostic/tree/master/apps/protoc-gen-openapi
option go_package = "./"; // only for proto swagger generator

// Interface exported by the server.
service HostIf {
  // TODO add server example host so we can use swagger to call services
  option (google.api.default_host) = "localhost"; // seems to have no effect

  // A simple RPC.

  rpc GetStation(StationName) returns (StationInfo) {
    
    option (google.api.http) = {
      get: "/v1/station"
    };
    option (google.api.method_signature) = "station";
  }

}

message StationName {
  string name = 1;
  Metadata metadata = 2;
  bool enabled = 3;
  optional uint64 dummy = 4;
}

message StationInfo {
  string name = 1;
  bool operational = 2;
}

message Metadata {
  map<string, string> data = 1;
}

```   
Generated openapi yaml ( optional was removed here ):
I don't know how an optional field should look like in json to be honest..  
Just ignoring would be an option to explicitly choose if needed, as in proto 3, I think every field is optional implicitly.  
Since ~3.17 or so you can add an optional tag, which implicitly wrap the field with a "oneof", so you can check for existance if I am right.  
  
Also it looks like all datatypes are converted to strings ...
I am using protoc version 3.17.3  

```
# Generated with protoc-gen-openapi
# https://github.com/google/gnostic/tree/master/apps/protoc-gen-openapi

openapi: 3.0.3
info:
    title: HostIf API
    description: Interface exported by the server.
    version: 0.0.1
servers:
    - url: http://127.0.0.1
paths:
    /v1/station:
        get:
            tags:
                - HostIf
            operationId: HostIf_GetStation
            parameters:
                - name: name
                  in: query
                  schema:
                    type: string
                - name: metadata
                  in: query
                  schema:
                    type: string
                - name: enabled
                  in: query
                  schema:
                    type: string
                - name: dummy
                  in: query
                  schema:
                    type: string
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/StationInfo'
components:
    schemas:
        StationInfo:
            properties:
                name:
                    type: string
                operational:
                    type: boolean
tags:
    - name: HostIf

```

**Comment by morphar** [comment]
Thank you 👍 
I will have a look at it and see what I can come up with.
I will have a look at the query params types as well.

With regards to how to convert: In JSON Schema everything is optional, unless stated otherwise with e.g. `required`. So in theory I think you're right, we could just ignore it, but that would cause loss of info from the proto. So I will try to see, if there's a way to avoid this knowledge loss... Though I doubt it.

**Comment by morphar** [comment]
FYI: Not breaking due to `optional` was easy.

But you also caught a problem with types, which I'm addressing as well.
This causes a little more pain, as http.proto and OpenAPI are not 100% compatible, specifically with regards to named path params, e.g.: `/v1/{name=shelves/*/books/*}`.

I should be able to have pull request done later today, maybe without handling the named path params differently than now, but with a fix to types on direct references, e.g. `/v1/shelves/{shelfId}/books/{bookId}`.

I noticed that you have:
```proto
message StationName {
  string name = 1;
  Metadata metadata = 2;
  bool enabled = 3;
  optional uint64 dummy = 4;
}

message Metadata {
  map<string, string> data = 1;
}
```
Just a note, if you weren't aware: the map can not be translated to query params and can therefore not be used in the request to `GetStation`.

**Comment by morphar** [comment]
@maxlein it proved a bit more cumbersome to fix the types, due to the fact that messages wasn't being handled, so I added that.
It should all work now (including optional), if the pull request gets merged.

**Comment by maxlein** [comment]
Thank you for the fast response!
Really appreciated!

**Comment by morphar** [comment]
You're welcome :)
I hope @timburks isn't on vacation (he's probably the one who will review the pull request) ;)

**Comment by timburks** [comment]
@morphar thanks for working on this! I have a question that I'll put on the PR, but otherwise LGTM

**Comment by morphar** [comment]
You're very welcome :)

**Comment by morphar** [comment]
@maxlein the changes have been merged, so everything should work now 👍

**Comment by jeffsawatzky** [comment]
@maxlein / @timburks  the related PR is closed so I think this can be closed now
