### ISSUE TITLE
Add validation of message output path to be able to run gnostic with only messages plugin

### ISSUE THREAD

**Issue by hojongs** [google/gnostic#287]
## Issue description

When I run the command below, I've got the error message `missing output directives`

```shell
gnostic --messages-out=. examples/v3.0/yaml/empty-v3.yaml
```

I think this is undesired behavior, it should generate `.messages.pb` files.
﻿
## Cause

https://github.com/google/gnostic/blob/c7a5e4fe8b3735c9ee03c475990e3b967db9a224/lib/gnostic.go#L407-L414

In the function `validateOptions`, it doesn't check messageOutputPath field.

## Suggested Change

```diff
	if g.binaryOutputPath == "" &&
		g.textOutputPath == "" &&
		g.yamlOutputPath == "" &&
		g.jsonOutputPath == "" &&
		g.errorOutputPath == "" &&
+		g.messageOutputPath == "" &&
		len(g.pluginCalls) == 0 {
		return NewUsageError("missing output directives")
	}
```

**Comment by timburks** [comment]
Fixed, thanks @hojongs !
