### ISSUE TITLE
openapi_out: How to overwrite operationId ?

### ISSUE THREAD

**Issue by max-os-lg** [google/gnostic#322]
I am trying to figure out, how I could overwrite the operationId with gnostic.  
Because in the documentation it looks bad if every endpoint is prefixed with the service name.  

I saw different proto annotation files for swagger and openapiv2, but nothing for v3.  

I just tried to get it working by using it like this:  

```
syntax = "proto3";

import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "protoc-gen-openapiv2/options/annotations.proto";

// we build swagger config with https://github.com/google/gnostic/tree/master/apps/protoc-gen-openapi
option go_package = "./"; // only for proto swagger generator

service TaskService {
  
  rpc Execute(TaskData) returns (TaskResponse) 
  {
      option (google.api.http) = {
        post: "/v1/execute"
        body: "*" // puts all message fields in body
      };
      option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
        operation_id: "OtherId";
      };
  }
}
```  

But I get no error and also no "OtherId" as operationId.  
OperationId is `TaskService_Execute`  

Should this be working with v3, or am I mixing up v2 with v3?

**Comment by jeffsawatzky** [comment]
@max-os-lg the grpc-gateway protoc-gen-openapiv2 gen is a completely different protoc-gen plugin than this one. That one is from:
https://github.com/grpc-ecosystem/grpc-gateway/tree/master/protoc-gen-openapiv2

The gnostic one doesn't support it's annotations, and by the looks of it, the gnostic one ONLY supports the defaulthost, http, and field_behavior annotations from googleapis.

I'm also looking for a way to customize the output, and it looks like we may need to add it ourselves...
