### ISSUE TITLE
protoc generate openapiv3 options usage

### ISSUE THREAD

**Issue by woyong** [google/gnostic#338]
protoc --proto_path=. \
	       --proto_path=./third_party \
 	       --openapi_out==paths=source_relative,naming=proto:. \
               xxxx.proto
protoc-gen-openapi: proto: cannot parse invalid wire-format data
--openapi_out: protoc-gen-openapi: Plugin failed with status code 1.
make: *** [api] Error 1

the naming option is ok?

**Comment by renyijiu** [comment]
You can use it like this  `--openapi_opt=enum_type=string`

**Comment by woyong** [comment]
> You can use it like this `--openapi_opt=enum_type=string`

thank you very much.
