### ISSUE TITLE
protoc-gen-openapi openapiv3 annotation not work

### ISSUE THREAD

**Issue by ppaanngggg** [google/gnostic#341]
I try to use the new feature #334  #339  on the latest commit. I found my custom openapiv3 annotation not merge into final schema.

Then I found the numbers are still 1042, maybe we need a rebuild of `openapiv3/annotations.proto`?

```go
var file_openapiv3_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*Document)(nil),
		Field:         1042,
		Name:          "openapi.v3.document",
		Tag:           "bytes,1042,opt,name=document",
		Filename:      "openapiv3/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Operation)(nil),
		Field:         1042,
		Name:          "openapi.v3.operation",
		Tag:           "bytes,1042,opt,name=operation",
		Filename:      "openapiv3/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*Schema)(nil),
		Field:         1042,
		Name:          "openapi.v3.schema",
		Tag:           "bytes,1042,opt,name=schema",
		Filename:      "openapiv3/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*Schema)(nil),
		Field:         1042,
		Name:          "openapi.v3.property",
		Tag:           "bytes,1042,opt,name=property",
		Filename:      "openapiv3/annotations.proto",
	},
}
```

**Comment by ppaanngggg** [comment]
@jeffsawatzky

**Comment by jeffsawatzky** [comment]
How are you importing the annotations.proto into your proto? Through buf.build or manually? The one on buf.build uses different package names which I think messes things up (though it looks like you did it manually)

I am currently doing everything manually and I build the protoc-gen-openapi cmd myself. You may need to do the same thing? Or use a version of the annotaions.proto that matches the one that protoc-gen-openapi was built against.

**Comment by ppaanngggg** [comment]
I did manually. Now I use the old version `annotations.proto` which number is 1042, then it works.

I think the latest `protoc-gen-openapi` still use number 1042, because [annotations.pb.go](https://github.com/google/gnostic/blob/master/openapiv3/annotations.pb.go) is 1042.

However the latest `annotations.proto` use number 1143, they are not matched now.

**Comment by jeffsawatzky** [comment]
@ppaanngggg hopefully #342 fixes the issue for you. Sorry for the confusion.

**Comment by ppaanngggg** [comment]
thanks to @jeffsawatzky 👍
