### ISSUE TITLE
openapiv3 proto files,  `go_package` is a relative path

### ISSUE THREAD

**Issue by ppaanngggg** [google/gnostic#343]
current go_package is `./openapiv3;openapi_v3`, I think `github.com/google/gnostic/openapiv3;openapi_v3` is better. I don't know there is any special purpose?

https://github.com/google/gnostic/blob/c1c54ff3ab436d41d0601b3777ef5d2dad388e1b/openapiv3/annotations.proto#L44
https://github.com/google/gnostic/blob/c1c54ff3ab436d41d0601b3777ef5d2dad388e1b/openapiv3/OpenAPIv3.proto#L45

@timburks @morphar

**Comment by timburks** [comment]
That seems ok to me - I may have made this relative (long ago) to ensure that this was a local import (during development), but the Go module system will take care of this now.

**Comment by ppaanngggg** [comment]
> That seems ok to me - I may have made this relative (long ago) to ensure that this was a local import (during development), but the Go module system will take care of this now.

I think I need to modify it, otherwise it's difficult to use `opanapiv3/annotations.proto` in other project using it.
