### ISSUE TITLE
additional_bindings not generate multiple paths

### ISSUE THREAD

**Issue by juchaosong** [google/gnostic#345]
We use `additional_bindings` to defice multiple URI bindings referring to [HTTP and gRPC Transcoding](https://google.aip.dev/127).
But it seems not generate multiple paths in openapi documentations.

I fork the repo, add commit https://github.com/juchaosong/gnostic/commit/5752cb1b52c4cfcb50bc4d6bc012ac7b681e6f75 using `additional_bindings`.
Use the following cmd to generate openapi.yaml:
```
cd cmd/protoc-gen-openapi
protoc -I examples/ --openapi_out=. examples/google/example/library/v1/library.proto
```
But only `POST /v1/shelves/{shelf}/books` generated.
Thanks for your respondings.

**Comment by timburks** [comment]
Thanks, agreed, we should add support for this.

**Comment by teone** [comment]
Following as I am also interested in this feature.
If someone can point me in the right direction I might find a little time to help with it.
