### ISSUE TITLE
protoc-gen-openapi: there are something wrong with the generated openapi.yaml when message's name is same

### ISSUE THREAD

**Issue by yzhaoyu** [google/gnostic#353]
I found that when I referred to proto A file there is A messge named View, and the proto that was referred to also referred to another proto B, B proto file also has a message named View, The generated View in openapi.yaml was not the view in proto A, it was replaced by the view in proto B.
proto A like this:
```proto
service Open {
  rpc GetView (View) returns (Response);
}

message View {
    string id = 1;
}

message File {
 protoB.Binary = 1;
}
```
proto B like this:
```proto
message View {
    string test = 1;
}

message Binary {
    int32 stream = 1;
}
```
The generated openapi.yaml contains  View of proto B, not View of proto A.
Is this a bug?

**Comment by timburks** [comment]
Thanks, this is certainly a possibility. Could you try using the `fq_schema_naming` option that @jeffsawatzky added? Do the results of that work for you?

**Comment by yzhaoyu** [comment]
> 

Thank you very much. This is very useful for me.

**Comment by yzhaoyu** [comment]
> Thanks, this is certainly a possibility. Could you try using the `fq_schema_naming` option that @jeffsawatzky added? Do the results of that work for you?

Thank you very much. This is very useful for me.
