### ISSUE TITLE
protoc-gen-openapi: wrong type for google.protobuf.UInt64Value and StringValue

### ISSUE THREAD

**Issue by EladSisu** [google/gnostic#360]
Both types: google.protobuf.UInt64Value  & google.protobuf.StringValue not getting converted correctly to openapi and is missing descriptions.

for example this proto : 

message Request {
  // A limit on the number of objects to be returned, between 1 and 100. 
  google.protobuf.UInt64Value limit = 1

getting converted into:

- name: limit.value
                  in: query
                  description: The uint64 value.
                  schema:
                    type: integer
                    format: uint64
                    
expected output : 

 - name: limit
          description: A limit on the number of objects to be returned, between 1 and 100.
          in: query
          required: false
          schema:
            type: int64
            format: uint64

**Comment by galihputera** [comment]
Hai maintainer team! We have a similar issue for protoc-gen-openapi. I already made an MR here https://github.com/google/gnostic/pull/366. Need your review

**Comment by jeffsawatzky** [comment]
@EladSisu / @galihputera now that #366 is merged, can this be closed?
