### ISSUE TITLE
protoc-gen-openapi output file name problem

### ISSUE THREAD

**Issue by code-tbd** [google/gnostic#376]
```
func (g *OpenAPIv3Generator) Run() error {
	d := g.buildDocumentV3()
	bytes, err := d.YAMLValue("Generated with protoc-gen-openapi\n" + infoURL)
	if err != nil {
		return fmt.Errorf("failed to marshal yaml: %s", err.Error())
	}
	outputFile := g.plugin.NewGeneratedFile("openapi.yaml", "")
	outputFile.Write(bytes)
	return nil
}
```
`protoc-gen-openapi` plays a significant role in my work, but it always generate the same files in the filename `openapi.yaml`.

I want a option to generate file with filename by origin filename.

For example, input file is named `helloworld.proto`, and I expect out file is named `helloworld_openapi.yaml`.

**Comment by shuqingzai** [comment]
I even wish it would be possible to pass a parameter custom name, if not pass the name parameter use something like you said
