### ISSUE TITLE
How do I define the proto file to generate custom fields in openai.yaml?

### ISSUE THREAD

**Issue by xuexuguang** [google/gnostic#383]
When I need to define the proto file, I will customize some fields so that openai.yaml can generate the corresponding fields.
As follows, I want to generate the summary field in openai.yaml, but I don't know how to define proto to normally generate such openai.yaml

This is my proto file
```code
service DotaService {
  rpc PlayerTransfer(dto.PlayerTransferReq)returns(dto.PlayerTransferResp){
    option (google.api.http) = {
      get: "/v1/api/dota2/player/transfer/{player_id}"
    };
  }
}
```

I expect to generate the openai.yaml file

```code
    /v1/api/dota2/player/transfer/{player_id}:
        get:
            tags:
                - DotaService
            summary: getPlayer
            operationId: DotaService_PlayerTransfer
            parameters:
                - name: player_id
                  in: path
                  description: 选手id
                  required: true
                  schema:
                    type: string
```

Thank you very much. I've been trying for a long time, but I can't find the answer

**Comment by jeffsawatzky** [comment]
@xuexuguang see this test as an example

https://github.com/google/gnostic/blob/ade94e0d08cb9c60272a311608cd5dabd30d1813/cmd/protoc-gen-openapi/examples/tests/openapiv3annotations/message.proto#L63

You can specify custom options

**Comment by xuexuguang** [comment]
Thank you very much. My problem is solved
