### ISSUE TITLE
Is there any correlation between "protoc-gen-openapi" and "protoc-gen-openapiv2"?

### ISSUE THREAD

**Issue by FGYFFFF** [google/gnostic#386]
Is this project related to "[protoc-gen-openapiv2](https://github.com/grpc-ecosystem/grpc-gateway/tree/main/protoc-gen-openapiv2)" under "grpc-gateway"? I noticed that a similar annotation is used.

**Comment by sagikazarmark** [comment]
As far as I know, they are not related.

**Comment by FGYFFFF** [comment]
thanks~ It seems that they implement the same ability to generate swagger.
